pipeline test 6

diff --git a/.github/workflows/deploy-camundafiles.yml b/.github/workflows/deploy-camundafiles.yml
--- a/.github/workflows/deploy-camundafiles.yml
+++ b/.github/workflows/deploy-camundafiles.yml
@@ -15,12 +15,18 @@ jobs:
 
     - name: Deploy Camunda Files
       run: |
-        #!/bin/bash
+            #!/bin/bash
 
             # Server URL
             SERVER_URL="http://10.0.24.77:30000/engine-rest/deployment/create"
 
-            # Dateien zum Hochladen
+            # Temporärer Ordner zum Speichern der heruntergeladenen Dateien
+            TEMP_DIR="c:/temp/camunda"
+
+            # Erstelle den temporären Ordner, falls er nicht existiert
+            mkdir -p "$TEMP_DIR"
+
+            # Dateien zum Herunterladen
             FILES=(
                 "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processesGrundgeruest.bpmn"
                 "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processesAnmeldeformular.form"
@@ -30,10 +36,7 @@ jobs:
                 "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processesAbholung.form"
             )
 
-            # Temporäres Verzeichnis erstellen
-            TEMP_DIR=$(mktemp -d)
-
-            # Iteriere über die Dateien, lade sie herunter und führe den curl-Befehl aus
+            # Herunterladen der Dateien in den temporären Ordner
             for FILE in "${FILES[@]}"
             do
                 BASENAME=$(basename "$FILE")
@@ -42,15 +45,32 @@ jobs:
                 echo "Downloading file: $FILE"
                 curl -s -o "$TEMP_FILE" "$FILE"
                 
+                if [ ! -f "$TEMP_FILE" ]; then
+                    echo "Error: Failed to download $FILE"
+                    exit 1
+                fi
+            done
+
+            # Hochladen der heruntergeladenen Dateien
+            for FILE in "${FILES[@]}"
+            do
+                BASENAME=$(basename "$FILE")
+                TEMP_FILE="$TEMP_DIR/$BASENAME"
+                
                 echo "Uploading file: $TEMP_FILE"
                 curl --location "$SERVER_URL" \
                     --header 'Content-Type: multipart/form-data' \
                     --form "upload=@$TEMP_FILE"
-                    
+                
+                if [ $? -ne 0 ]; then
+                    echo "Error: Failed to upload $TEMP_FILE"
+                    exit 1
+                fi
+                
                 sleep 1
             done
 
-            # Temporäres Verzeichnis bereinigen
+            # Bereinigen des temporären Ordners
             rm -r "$TEMP_DIR"
 
             echo "All files have been successfully uploaded."
